name: "🐛 Bug Report"
description: Create a report to help improve this plugint
title: "[BUG] <title>"
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: "A clear and concise description of what the bug is."
    validations:
      required: true
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to reproduce the behavior
      description: "A list of actions to take to reproduce the issue."
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected behavior
      description: "A clear and concise description of what you expected to happen."
    validations:
      required: true
  - type: textarea
    id: screenshots_codesnippets
    attributes:
      label: Screenshots / Code snippets
      description: "If applicable, add screenshots/code snippets to help explain your problem."
  - type: input
    id: node_version
    attributes:
      label: Node version
    validations:
      required: true
  - type: input
    id: strapi_version
    attributes:
      label: Strapi version
    validations:
      required: true
  - type: input
    id: plugin_version
    attributes:
      label: Plugin version
    validations:
      required: true
  - type: input
    id: database_type
    attributes:
      label: Database
    validations:
      required: true
  - type: input
    id: operating_system
    attributes:
      label: Operating system
    validations:
      required: true
  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: "Add any other context about the problem here."
